"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
command_timeout = 20

format = "$directory$git_branch$git_status$c$rust$golang$nodejs$python$cmd_duration$line_break$character"

palette = "apple-ribbon"

[directory]
format = "[](fg:color_path)[󰀵 $path](fg:base bg:color_path)[](fg:color_path)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
format = " [](fg:color_git)[$symbol$branch](fg:base bg:color_git)[](fg:color_git)"

[git_status]
format = "([ $all_status$ahead_behind](fg:color_git))"

[c]
format = " [](fg:color_lang)[$symbol$version](fg:base bg:color_lang)[](fg:color_lang)"

[rust]
format = " [](fg:color_lang)[$symbol$version](fg:base bg:color_lang)[](fg:color_lang)"

[golang]
format = " [](fg:color_lang)[$symbol$version](fg:base bg:color_lang)[](fg:color_lang)"

[nodejs]
format = " [](fg:color_lang)[$symbol$version](fg:base bg:color_lang)[](fg:color_lang)"

[python]
format = " [](fg:color_lang)[$symbol$version](fg:base bg:color_lang)[](fg:color_lang)"

[cmd_duration]
show_milliseconds = false
format = " [$duration](fg:color_time)"
min_time = 1000

[character]
success_symbol = "[❯](bold fg:color_path)"
error_symbol = "[❯](bold red)"

[palettes.apple-ribbon]
color_path = "#61BB46"
color_git  = "#009DDC"
color_lang = "#F5821F"
color_time = "#963D97"
base       = "#282a36"
